#!/usr/bin/env bash
set -euo pipefail

# ---- Firewall / network policy (used for per-workspace .conf) ----
DNS_RESOLVER_IP="192.168.0.1"          # always whitelisted (used for --dns too)
WHITELIST_EXTRA=""                     # additional CIDRs to whitelist, comma-separated
                                       # e.g. "10.10.0.5/32,203.0.113.0/24"
BLACKLIST_CIDRS="10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.0/8,169.254.0.0/16"
FIREWALL_CONF_DIR="/etc/devcontainer-firewall/containers"
# ------------------------------------------------------------------

usage() {
  echo "Usage: $0 <workspace-folder>"
  exit 1
}

[[ $# -eq 1 ]] || usage
WORKSPACE="$(realpath "$1")"
[[ -d "$WORKSPACE" ]] || { echo "Error: workspace folder does not exist: $WORKSPACE"; exit 1; }

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# ---- 1) Create dev container settings ----
echo "[dev-sandbox] Creating devcontainer.json..."

# devcontainer settings must be created/owned by the current user
DEVCONTAINER_DIR="$WORKSPACE/.devcontainer"
DEVCONTAINER_JSON="$DEVCONTAINER_DIR/devcontainer.json"
mkdir -p "$DEVCONTAINER_DIR"

# If you want literally identical content, paste your existing devcontainer.json heredoc here.
if [[ ! -f "$DEVCONTAINER_JSON" ]]; then
  cat > "$DEVCONTAINER_JSON" <<EOF
{
  "name": "dev-sandbox",
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
  "workspaceMount": "source=\${localWorkspaceFolder},target=/home/vscode/\${localWorkspaceFolderBasename},type=bind,consistency=cached",
  "workspaceFolder": "/home/vscode/\${localWorkspaceFolderBasename}",
  "remoteUser": "vscode",
  "shutdownAction": "stopContainer",
  "runArgs": [
    "--network=bridge",
    "--cap-drop=ALL",
    "--security-opt=no-new-privileges:true",
    "--dns=${DNS_RESOLVER_IP}",
    "--label=dev-sandbox=true",
    "--label=dev-sandbox-config=$(basename "$WORKSPACE")"
  ],
  "features": {
    "ghcr.io/devcontainers/features/common-utils:2": {},
    "ghcr.io/devcontainers/features/git:1": {},
    "ghcr.io/devcontainers/features/python:1": {},
    "ghcr.io/devcontainers/features/aws-cli:1": {},
    "ghcr.io/devcontainers/features/docker-in-docker:2": {},
    "ghcr.io/devcontainers/features/node:1": {},
  },
  "postCreateCommand": "npm install -g @anthropic-ai/claude-code @openai/codex",
  "customizations": {
    "vscode": {
      "extensions": [
        "anthropic.claude-code",
        "openai.chatgpt",
        "streetsidesoftware.code-spell-checker"
      ],
      "settings": {
        "remote.extensionKind": {
          "anthropic.claude-code": [ "workspace" ],
          "openai.chatgpt": [ "workspace" ]
        }
      }
    }
  }
}
EOF
else
  echo "[dev-sandbox] Using existing .devcontainer/devcontainer.json"
fi

# ---- 2) Create per-workspace firewall config (optional) ----
CONF_NAME="$(basename "$WORKSPACE")"
CONF_FILE="$FIREWALL_CONF_DIR/${CONF_NAME}.conf"

# Build whitelist: DNS resolver + any extra CIDRs
WHITELIST_CIDRS="${DNS_RESOLVER_IP}/32"
[[ -n "$WHITELIST_EXTRA" ]] && WHITELIST_CIDRS="${WHITELIST_CIDRS},${WHITELIST_EXTRA}"

if [[ ! -f "$CONF_FILE" ]]; then
  echo "[dev-sandbox] Creating firewall config: $CONF_FILE"
  sudo tee "$CONF_FILE" > /dev/null <<EOF
# Auto-generated by start-sandbox.sh for workspace: $WORKSPACE
WHITELIST=${WHITELIST_CIDRS}
BLACKLIST=${BLACKLIST_CIDRS}
EOF
  echo "[dev-sandbox] Firewall config created."
else
  echo "[dev-sandbox] Using existing firewall config: $CONF_FILE"
fi

# ---- 3) Create dev container (optional) ----
DEVCONTAINER_CLI=""
CID=""

if [ -x "./node_modules/.bin/devcontainer" ]; then
  DEVCONTAINER_CLI="./node_modules/.bin/devcontainer"
elif command -v devcontainer >/dev/null 2>&1; then
  DEVCONTAINER_CLI="devcontainer"
fi

if [ -n "$DEVCONTAINER_CLI" ]; then
  echo "[dev-sandbox] Using devcontainer CLI: $DEVCONTAINER_CLI"
  "$DEVCONTAINER_CLI" up --workspace-folder $WORKSPACE || echo "[dev-sandbox] devcontainer up failed; continuing"

  CID=$(docker ps \
  --filter "label=devcontainer.local_folder=$WORKSPACE" \
  --format "{{.ID}}" | head -n1)
  echo "[dev-sandbox] Found devcontainer $CID"
else
  echo "[dev-sandbox] devcontainer CLI not found; continuing"
fi
# --- ----

# ---- 4) Open VS Code detached as the current user ----
if [ -n "$CID" ]; then
  echo "[dev-sandbox] Opening VS Code: attaching to dev container $CID"
  code --new-window  --folder-uri "vscode-remote://attached-container+$(printf "$CID" | xxd -p)/home/vscode/$(basename "$WORKSPACE")" >/dev/null 2>&1 || true
else
  echo "[dev-sandbox] Opening VS Code: $WORKSPACE"
  code --new-window "$WORKSPACE" >/dev/null 2>&1 || true
fi
# ----  ----
